name: accessibility-alt-text-bot
on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]
  issue_comment:
    types: [created, edited, deleted]
  discussion:
    types: [created, edited]
  discussion_comment:
    types: [created, edited, deleted]

permissions:
  issues: write
  pull-requests: write
  discussions: write

jobs:
  accessibility_alt_text_bot:
    runs-on: ubuntu-latest
    steps:
       - uses: github/accessibility-alt-text-bot@7e895d46677f15841def9acef1239ea7c12593a5 # v1.7.3
